# gokaygurcan/dockerfile-nginx

language: bash
services: docker

sudo: false

git:
  depth: 1

before_script:
  - docker version
  - docker info

script:
  - docker build --rm --build-arg MAXMIND_LICENSE_KEY=$MAXMIND_LICENSE_KEY -t gokaygurcan/nginx:test .
  - docker run --rm -d --name nginx -p 80:80 gokaygurcan/nginx:test
  - docker exec nginx nginx -V
  - curl -I http://localhost:80

notifications:
  email: false
