# https://github.com/DataDog/nginx-datadog/blob/master/doc/API.md

datadog_service_name                                "nginx";
datadog_environment                                 "production";       
datadog_version                                     "1.16.0";
datadog_sample_rate                                 1.0;
datadog_agent_url                                   http://localhost:8126;
datadog_tags                                        "env:production";
datadog_tracing                                     on; 
datadog_appsec_enabled                              on;
datadog_waf_thread_pool_name                        waf_thread_pool;
