# gokaygurcan/dockerfile-nginx

name: nginx

on:
  push:
  pull_request:
    branches:
    - main

env:
  GITHUB: ${{ toJson(github) }}

jobs:
  version:
    name: version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - id: version
      name: Version
      run: |
        grep -r "NGINX_VERSION=" Dockerfile | cut -d "=" -f 2 | cut -d " " -f 1
        echo "{version}={$(grep -r "NGINX_VERSION=" Dockerfile | cut -d "=" -f 2 | cut -d " " -f 1)}" >> $GITHUB_OUTPUT

  nginx:
    name: nginx
    runs-on: ubuntu-latest
    needs: [ version ]
    env:
      CI: true
    steps:
    - id: sanity-check
      name: Sanity check
      run: |
        printenv

    - id: checkout
      name: Checkout
      uses: actions/checkout@v3

    - id: login
      name: Login to Docker Hub
      uses: docker/login-action@v2
      if: |
        github.ref == 'refs/heads/main'
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - id: build
      name: Build image
      run: |
        docker build --file Dockerfile --tag gokaygurcan/nginx:latest --tag gokaygurcan/nginx:${{ needs.version.outputs.version }} .
        docker ps -a

    - id: test
      name: Test
      run: |
        docker volume create usr-share-geoip
        docker run --rm --name geoipupdate -v usr-share-geoip:/usr/share/GeoIP -e GEOIPUPDATE_FREQUENCY=0 -e GEOIPUPDATE_ACCOUNT_ID='${{ secrets.GEOIPUPDATE_ACCOUNT_ID }}' -e GEOIPUPDATE_LICENSE_KEY='${{ secrets.GEOIPUPDATE_LICENSE_KEY }}' -e GEOIPUPDATE_EDITION_IDS='GeoLite2-City GeoLite2-Country' maxmindinc/geoipupdate
        docker run --rm --name nginx gokaygurcan/nginx nginx -V

    - id: push
      name: Push to Docker Registry
      uses: docker/build-push-action@v3
      if: |
        github.ref == 'refs/heads/main'
      with:
        context: .
        push: true
        tags: |
          gokaygurcan/nginx:latest
          gokaygurcan/nginx:${{ needs.version.outputs.version }}
