# gokaygurcan/dockerfile-nginx

name: nginx

on:
  push:
  pull_request:
    branches:
    - main

permissions:
  contents: read

env:
  GITHUB: ${{ toJson(github) }}
  SHA: ${{ github.event.pull_request.head.sha || github.event.after }}

jobs:
  nginx:
    name: nginx
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
    - id: sanity-check
      name: Sanity check
      run: |
        printenv

    - id: checkout
      name: Checkout
      uses: actions/checkout@v6

    - id: qemu
      name: Set up QEMU
      uses: docker/setup-qemu-action@v4

    - id: buildx
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
      with:
        platforms: linux/amd64,linux/arm64

    - id: build
      name: Build image
      run: |
        docker buildx build --file Dockerfile --tag gokaygurcan/nginx:latest --load .
        docker ps -a

    - id: test
      name: Test
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ]; then
          docker volume create usr-share-geoip
          docker run --rm --name geoipupdate -v usr-share-geoip:/usr/share/GeoIP -e GEOIPUPDATE_FREQUENCY=0 -e GEOIPUPDATE_ACCOUNT_ID='${{ secrets.GEOIPUPDATE_ACCOUNT_ID }}' -e GEOIPUPDATE_LICENSE_KEY='${{ secrets.GEOIPUPDATE_LICENSE_KEY }}' -e GEOIPUPDATE_EDITION_IDS='GeoLite2-City GeoLite2-Country' maxmindinc/geoipupdate
        fi
        docker run --rm --name nginx gokaygurcan/nginx nginx -V

    - id: meta
      name: Generate image metadata
      uses: docker/metadata-action@v6
      with:
        images: gokaygurcan/nginx
        labels: |
          org.opencontainers.image.revision=${{ env.SHA }}
        tags: |
          type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
          type=ref,event=pr
          type=semver,pattern=v{{version}}
          type=sha,prefix=,suffix=,format=short,enable=${{ github.event_name == 'pull_request' }}

    - id: login
      name: Login to Docker Hub
      uses: docker/login-action@v4
      if: |
        github.ref == 'refs/heads/main' ||
        (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - id: push
      name: Push to Docker Registry
      uses: docker/build-push-action@v7
      if: |
        github.ref == 'refs/heads/main' ||
        (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
