# gokaygurcan/dockerfile-nginx

name: 'NGINX'

on:
  push:
  pull_request:
    branches:
    - master

env:
  GITHUB: ${{ toJson(github) }}

jobs:
  nginx:
    name: 'nginx'
    runs-on: 'ubuntu-latest'
    env:
      CI: true
    steps:
    - id: 'checkout'
      name: 'Checkout'
      uses: 'actions/checkout@v2'

    - id: 'login'
      name: 'Login to Docker Hub'
      uses: 'actions-hub/docker/login@master'
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - id: 'build'
      name: 'Build image'
      run: |
        docker build --file Dockerfile --build-arg MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }} --tag gokaygurcan/nginx:latest .

    - id: 'test'
      name: 'Test'
      run: |
        docker run --rm gokaygurcan/nginx nginx -V

    - id: 'push'
      name: 'Push to Docker Registry'
      uses: 'actions-hub/docker@master'
      if: github.ref == 'refs/heads/master'
      with:
        args: push gokaygurcan/nginx:latest
