# gokaygurcan/dockerfile-nginx

name: 'NGINX'

on:
  push:
  pull_request:
    branches:
    - master

env:
  GITHUB: ${{ toJson(github) }}

jobs:
  nginx:
    name: 'nginx'
    runs-on: 'ubuntu-latest'
    env:
      CI: true
    steps:
    - id: 'checkout'
      name: 'Checkout'
      uses: 'actions/checkout@v2'

    - id: 'login'
      name: 'Login to Docker Hub'
      uses: 'actions-hub/docker/login@master'
      if: github.ref == 'refs/heads/master'
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - id: 'build'
      name: 'Build image'
      run: |
        docker build --file Dockerfile --tag gokaygurcan/nginx:latest .

    - id: 'test'
      name: 'Test'
      run: |
        docker volume create usr-share-geoip
        docker run --rm --name geoipupdate -v usr-share-geoip:/usr/share/GeoIP -e GEOIPUPDATE_FREQUENCY=0 -e GEOIPUPDATE_ACCOUNT_ID='${{ secrets.GEOIPUPDATE_ACCOUNT_ID }}' -e GEOIPUPDATE_LICENSE_KEY='${{ secrets.GEOIPUPDATE_LICENSE_KEY }}' -e GEOIPUPDATE_EDITION_IDS='GeoLite2-City GeoLite2-Country' maxmindinc/geoipupdate
        docker run --rm --name nginx gokaygurcan/nginx nginx -V

    - id: 'push'
      name: 'Push to Docker Registry'
      uses: 'actions-hub/docker@master'
      if: github.ref == 'refs/heads/master'
      with:
        args: push gokaygurcan/nginx:latest
